#!/bin/bash

set -e

cat <<'EOF' >> /lib/systemd/system/wisnuc-installer.service
[Unit]
Description=Wisnuc Installer
Before=getty@tty1.service
After=multi-user.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash /usr/bin/wisnuc-installer
StandardInput=tty
StandardOutput=inherit
StandardError=inherit

[Install]
WantedBy=multi-user.target
EOF

cat <<'EOF' >> /usr/bin/wisnuc-installer
#!/bin/bash

set -e

URL=https://raw.githubusercontent.com/wisnuc/appifi-system/master/install-scripts/ubuntu-16-04-2-amd64/install-appifi.sh
SHA1=/wisnuc/bootstrap/appifi-bootstrap.js.sha1
UPDATE=/wisnuc/bootstrap/appifi-bootstrap-update.packed.js

if [ -f $SHA1 ] || [ -f $UPDATE ]; then exit 0; fi

curl -s $URL | bash - 2>&1 | tee /.wisnuc-install.log
systemctl disable wisnuc-installer.service; fi
EOF

systemctl enable wisnuc-installer.service



